<template><div><h1 id="版本-1-数据结构和前端界面" tabindex="-1"><a class="header-anchor" href="#版本-1-数据结构和前端界面"><span>版本 1 - 数据结构和前端界面</span></a></h1>
<p>第 1 个版本的代码 <em>goto_v1</em> 见 <a href="examples/chapter_19/goto_v1">goto_v1</a>。</p>
<h1 id="_19-3-数据结构" tabindex="-1"><a class="header-anchor" href="#_19-3-数据结构"><span>19.3 数据结构</span></a></h1>
<p>（本节代码见 <a href="examples/chapter_19/goto_v1/store.go">goto_v1/store.go</a>。）</p>
<p>当程序运行在生产环境时，会收到很多短网址的请求，同时会有一些将长 URL 转换成短 URL 的请求。我们的程序要以什么样的结构存储这些数据呢？<RouteLink to="/chapter-4/19.2.html">19.2 节</RouteLink>中 (A) 和 (B) 两种 URL 都是字符串，此外，它们相互关联：给定键 (B) 能获取到值 (A)，他们互相<em>映射</em> (map)。要将数据存储在内存中，我们需要这种结构，它们几乎存在于所有的编程语言中，只是名称有所不同，例如“哈希表”或“字典”等。</p>
<p>Go 语言就有这种内建的映射 (map)：<code v-pre>map[string]string</code>。</p>
<p>键的类型写在 <code v-pre>[</code> 和 <code v-pre>]</code> 之间，紧接着是值的类型。有关映射的所有知识详见 <RouteLink to="/chapter-4/08.0.html">8 章</RouteLink>。为特定类型指定一个别名在严谨的程序中非常实用。Go 语言中通过关键字 <code v-pre>type</code> 来定义，因此有定义：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token keyword">type</span> URLStore <span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span><span class="token builtin">string</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>它从短 URL 映射到长 URL，两者都是字符串。</p>
<p>要创建那种类型的变量，并命名为 <code v-pre>m</code>，使用：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line">m <span class="token operator">:=</span> <span class="token function">make</span><span class="token punctuation">(</span>URLStore<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>假设 <em>http://goto/a</em> 映射到 <em>http://google.com/</em> ，我们要把它们存储到 m 中，可以用如下语句：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line">m<span class="token punctuation">[</span><span class="token string">"a"</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token string">"http://google.com/"</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>（键只是 <em>http://goto/</em> 的后缀，其前缀总是不变的。）</p>
<p>要获得给定 &quot;a&quot; 对应的长 URL，可以这么写：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line">url <span class="token operator">:=</span> m<span class="token punctuation">[</span><span class="token string">"a"</span><span class="token punctuation">]</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>此时 <code v-pre>url</code> 的值等于 <code v-pre>http://google.com/</code>。</p>
<p>注意，使用了 <code v-pre>:=</code> 就不需要指明 url 的类型为 <code v-pre>string</code>，编译器会从右侧的值中推断出来。</p>
<h2 id="使程序线程安全" tabindex="-1"><a class="header-anchor" href="#使程序线程安全"><span>使程序线程安全</span></a></h2>
<p>这里，变量 <code v-pre>URLStore</code> 是中心化的内存存储。当收到网络流量时，会有很多 <code v-pre>Redirect</code> 服务的请求。这些请求其实只涉及读操作：以给定的短 URL 作为键，返回对应的长 URL 的值。然而，对 <code v-pre>Add</code> 服务的请求则大不相同，它们会更改 <code v-pre>URLStore</code>，添加新的键值对。当在瞬间收到大量更新请求时，可能会产生如下问题：添加操作可能被另一个同类请求打断，写入的长 URL 值可能会丢失；另外，读取和更改同时进行，导致可能读到脏数据。代码中的 <code v-pre>map</code> 并不保证当开始更新数据时，会彻底阻止另一个更新操作的启动。也就是说，<code v-pre>map</code> 不是线程安全的，goto 会并发地为很多请求提供服务。因此必须使 <code v-pre>URLStore</code> 是线程安全的，以便可以从不同的线程访问它。最简单和经典的方法是为其增加一个锁，它是 Go 标准库 <code v-pre>sync</code> 包中的 <code v-pre>Mutex</code> 类型，必须导入到我们的代码中（关于锁详见 <RouteLink to="/chapter-4/09.3.html">9.3 节</RouteLink>）。</p>
<p>现在，我们把 <code v-pre>URLStore</code> 类型的定义更改为一个结构体（就是字段的集合，类似 C 或 Java ，<RouteLink to="/chapter-4/10.0.html">10 章</RouteLink> 介绍了结构体），它含有两个字段：<code v-pre>map</code> 和 <code v-pre>sync</code> 包的 <code v-pre>RWMutex</code>：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token string">"sync"</span></span>
<span class="line"><span class="token keyword">type</span> URLStore <span class="token keyword">struct</span> <span class="token punctuation">{</span></span>
<span class="line">	urls <span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span><span class="token builtin">string</span>		<span class="token comment">// map from short to long URLs</span></span>
<span class="line">	mu sync<span class="token punctuation">.</span>RWMutex</span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>RWMutex</code> 有两种锁：分别对应读和写。多个客户端可以同时设置读锁，但只有一个客户端可以设置写锁（以排除所有的读锁），有效地串行化变更，使他们按顺序生效。</p>
<p>我们将在 <code v-pre>Get()</code> 函数中实现 <code v-pre>Redirect</code> 服务的读请求，在 <code v-pre>Set</code> 函数中实现 <code v-pre>Add</code> 服务的写请求。<code v-pre>Get()</code> 函数类似下面这样：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token keyword">func</span> <span class="token punctuation">(</span>s <span class="token operator">*</span>URLStore<span class="token punctuation">)</span> <span class="token function">Get</span><span class="token punctuation">(</span>key <span class="token builtin">string</span><span class="token punctuation">)</span> <span class="token builtin">string</span> <span class="token punctuation">{</span></span>
<span class="line">	s<span class="token punctuation">.</span>mu<span class="token punctuation">.</span><span class="token function">RLock</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">	url <span class="token operator">:=</span> s<span class="token punctuation">.</span>urls<span class="token punctuation">[</span>key<span class="token punctuation">]</span></span>
<span class="line">	s<span class="token punctuation">.</span>mu<span class="token punctuation">.</span><span class="token function">RUnlock</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token keyword">return</span> url</span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>函数按照键（短 URL）返回对应映射后的 URL。它所处理的变量是指针类型（见 <RouteLink to="/chapter-4/04.9.html">4.9 节</RouteLink>），指向 <code v-pre>URLStore</code>。但在读取值之前，先用 <code v-pre>s.mu.RLock()</code> 放置一个读锁，这样就不会有更新操作妨碍读取。数据读取后撤销锁定，以便挂起的更新操作可以开始。如果键不存在于 map 中会怎样？会返回字符串的零值（空字符串）。注意点号 (<code v-pre>.</code>) 类似面向对象的语言：在 <code v-pre>s</code> 的 <code v-pre>mu</code> 字段上调用方法 <code v-pre>RLock()</code>。</p>
<p><code v-pre>Set()</code> 函数同时需要 URL 的键值对，且必须放置写锁 <code v-pre>Lock()</code> 来排除同一时刻任何其他更新操作。函数返回布尔值 <code v-pre>true</code> 或 <code v-pre>false</code> 来表示 <code v-pre>Set()</code> 操作是否成功：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token keyword">func</span> <span class="token punctuation">(</span>s <span class="token operator">*</span>URLStore<span class="token punctuation">)</span> <span class="token function">Set</span><span class="token punctuation">(</span>key<span class="token punctuation">,</span> url <span class="token builtin">string</span><span class="token punctuation">)</span> <span class="token builtin">bool</span> <span class="token punctuation">{</span></span>
<span class="line">	s<span class="token punctuation">.</span>mu<span class="token punctuation">.</span><span class="token function">Lock</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token boolean">_</span><span class="token punctuation">,</span> present <span class="token operator">:=</span> s<span class="token punctuation">.</span>urls<span class="token punctuation">[</span>key<span class="token punctuation">]</span></span>
<span class="line">	<span class="token keyword">if</span> present <span class="token punctuation">{</span></span>
<span class="line">		s<span class="token punctuation">.</span>mu<span class="token punctuation">.</span><span class="token function">Unlock</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">		<span class="token keyword">return</span> <span class="token boolean">false</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line">	s<span class="token punctuation">.</span>urls<span class="token punctuation">[</span>key<span class="token punctuation">]</span> <span class="token operator">=</span> url</span>
<span class="line">	s<span class="token punctuation">.</span>mu<span class="token punctuation">.</span><span class="token function">Unlock</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token keyword">return</span> <span class="token boolean">true</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>形式 <code v-pre>_, present := s.urls[key]</code> 可以测试 <code v-pre>map</code> 中是否已经包含该键，包含则 <code v-pre>present</code> 为 <code v-pre>true</code>，否则为 <code v-pre>false</code>。这种形式称为“逗号 ok 模式”，在 Go 代码中会频繁出现。如果键已存在，<code v-pre>Set()</code> 函数直接返回布尔值 <code v-pre>false</code>，<code v-pre>map</code> 不会被更新（这样可以保证短 URL 不会重复）。如果键不存在，把它加入 <code v-pre>map</code> 中并返回 <code v-pre>true</code>。左侧 <code v-pre>_</code> 是一个值的占位符，赋值给 <code v-pre>_</code> 来表明我们不会使用它。注意在更新后尽早调用 <code v-pre>Unlock()</code> 来释放对 <code v-pre>URLStore</code> 的锁定。</p>
<h2 id="使用-defer-简化代码" tabindex="-1"><a class="header-anchor" href="#使用-defer-简化代码"><span>使用 defer 简化代码</span></a></h2>
<p>目前代码还比较简单，容易记得操作完成后调用 <code v-pre>Unlock()</code> 解锁。然而在代码更复杂时很容易忘记解锁，或者放置在错误的位置，往往导致问题很难追踪。对于这种情况 Go 提供了一个特殊关键字 <code v-pre>defer</code>（见 <RouteLink to="/chapter-4/06.4.html">6.4 节</RouteLink>）。在本例中，可以在 <code v-pre>Lock()</code> 之后立即示意 <code v-pre>Unlock()</code>，不过其效果是 <code v-pre>Unlock()</code> 只会在函数返回之前被调用。</p>
<p><code v-pre>Get()</code> 可以简化成以下代码（我们消除了本地变量 <code v-pre>url</code>）：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token keyword">func</span> <span class="token punctuation">(</span>s <span class="token operator">*</span>URLStore<span class="token punctuation">)</span> <span class="token function">Get</span><span class="token punctuation">(</span>key <span class="token builtin">string</span><span class="token punctuation">)</span> <span class="token builtin">string</span> <span class="token punctuation">{</span></span>
<span class="line">	s<span class="token punctuation">.</span>mu<span class="token punctuation">.</span><span class="token function">RLock</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token keyword">defer</span> s<span class="token punctuation">.</span>mu<span class="token punctuation">.</span><span class="token function">RUnlock</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token keyword">return</span> s<span class="token punctuation">.</span>urls<span class="token punctuation">[</span>key<span class="token punctuation">]</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>Set()</code> 的逻辑在某种程度上也变得清晰了（我们不用再考虑解锁的事了）：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token keyword">func</span> <span class="token punctuation">(</span>s <span class="token operator">*</span>URLStore<span class="token punctuation">)</span> <span class="token function">Set</span><span class="token punctuation">(</span>key<span class="token punctuation">,</span> url <span class="token builtin">string</span><span class="token punctuation">)</span> <span class="token builtin">bool</span> <span class="token punctuation">{</span></span>
<span class="line">	s<span class="token punctuation">.</span>mu<span class="token punctuation">.</span><span class="token function">Lock</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token keyword">defer</span> s<span class="token punctuation">.</span>mu<span class="token punctuation">.</span><span class="token function">Unlock</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token boolean">_</span><span class="token punctuation">,</span> present <span class="token operator">:=</span> s<span class="token punctuation">.</span>urls<span class="token punctuation">[</span>key<span class="token punctuation">]</span></span>
<span class="line">	<span class="token keyword">if</span> present <span class="token punctuation">{</span></span>
<span class="line">		<span class="token keyword">return</span> <span class="token boolean">false</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line">	s<span class="token punctuation">.</span>urls<span class="token punctuation">[</span>key<span class="token punctuation">]</span> <span class="token operator">=</span> url</span>
<span class="line">	<span class="token keyword">return</span> <span class="token boolean">true</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="urlstore-工厂函数" tabindex="-1"><a class="header-anchor" href="#urlstore-工厂函数"><span>URLStore 工厂函数</span></a></h2>
<p><code v-pre>URLStore()</code> 结构体中包含 <code v-pre>map</code> 类型的字段，使用前必须先用 <code v-pre>make()</code> 初始化。在 Go 中创建一个结构体实例，一般是通过定义一个前缀为 <code v-pre>New</code>，能返回该类型已初始化实例的函数（通常是指向实例的指针）。</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token keyword">func</span> <span class="token function">NewURLStore</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">*</span>URLStore <span class="token punctuation">{</span></span>
<span class="line">	<span class="token keyword">return</span> <span class="token operator">&amp;</span>URLStore<span class="token punctuation">{</span> urls<span class="token punctuation">:</span> <span class="token function">make</span><span class="token punctuation">(</span><span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span><span class="token builtin">string</span><span class="token punctuation">)</span> <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>在 <code v-pre>return</code> 语句中，创建了 <code v-pre>URLStore</code> 字面量实例，其中包含初始化了的 <code v-pre>map</code> 映射。锁无需特别指明初始化，这是 Go 创建结构体实例的惯例。<code v-pre>&amp;</code> 是取址运算符，它将我们要返回的内容变成指针，因为 <code v-pre>NewURLStore()</code> 返回类型是 <code v-pre>*URLStore</code>。然后调用该函数来创建 <code v-pre>URLStore</code> 变量：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token keyword">var</span> store <span class="token operator">=</span> <span class="token function">NewURLStore</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="使用-urlstore" tabindex="-1"><a class="header-anchor" href="#使用-urlstore"><span>使用 URLStore</span></a></h2>
<p>要新增一对短/长 URL 到 <code v-pre>map</code> 中，我们只需调用 <code v-pre>s</code> 上的 <code v-pre>Set()</code> 方法，由于返回布尔值，可以把它包裹在 <code v-pre>if</code> 语句中：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token keyword">if</span> s<span class="token punctuation">.</span><span class="token function">Set</span><span class="token punctuation">(</span><span class="token string">"a"</span><span class="token punctuation">,</span> <span class="token string">"http://google.com"</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">	<span class="token comment">// 成功</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>要获取给定短 URL 对应的长 URL，调用 <code v-pre>s</code> 上的 <code v-pre>Get()</code> 方法，将返回值放入变量 <code v-pre>url</code>：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token keyword">if</span> url <span class="token operator">:=</span> s<span class="token punctuation">.</span><span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"a"</span><span class="token punctuation">)</span><span class="token punctuation">;</span> url <span class="token operator">!=</span> <span class="token string">""</span> <span class="token punctuation">{</span></span>
<span class="line">	<span class="token comment">// 重定向到 url</span></span>
<span class="line"><span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span></span>
<span class="line">	<span class="token comment">// 键未找到</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>这里我们利用 Go 语言 <code v-pre>if</code> 语句的特性，可以在起始部分、条件判断前放置初始化语句。另外还需要一个 <code v-pre>Count()</code> 方法以获取 <code v-pre>map</code> 中键值对的数量，可以使用内建的 <code v-pre>len()</code> 函数：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token keyword">func</span> <span class="token punctuation">(</span>s <span class="token operator">*</span>URLStore<span class="token punctuation">)</span> <span class="token function">Count</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token builtin">int</span> <span class="token punctuation">{</span></span>
<span class="line">	s<span class="token punctuation">.</span>mu<span class="token punctuation">.</span><span class="token function">RLock</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token keyword">defer</span> s<span class="token punctuation">.</span>mu<span class="token punctuation">.</span><span class="token function">RUnlock</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token keyword">return</span> <span class="token function">len</span><span class="token punctuation">(</span>s<span class="token punctuation">.</span>urls<span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>如何根据给定的长 URL 计算出短 URL 呢？为此我们创建一个函数 <code v-pre>genKey(n int) string {…}</code>，将 <code v-pre>s.Count()</code> 的当前值作为其整型参数传入。（具体算法并不重要，示例代码可以在 <a href="examples/chapter_19/goto_v1/key.go">key.go</a> 找到。）</p>
<p>现在，我们可以创建一个 <code v-pre>Put()</code> 方法，接收一个长 URL，用 <code v-pre>genKey()</code> 生成其短 URL 键，调用 <code v-pre>Set()</code> 方法在此键下存储长 URL 数据，然后返回这个键：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token keyword">func</span> <span class="token punctuation">(</span>s <span class="token operator">*</span>URLStore<span class="token punctuation">)</span> <span class="token function">Put</span><span class="token punctuation">(</span>url <span class="token builtin">string</span><span class="token punctuation">)</span> <span class="token builtin">string</span> <span class="token punctuation">{</span></span>
<span class="line">	<span class="token keyword">for</span> <span class="token punctuation">{</span></span>
<span class="line">		key <span class="token operator">:=</span> <span class="token function">genKey</span><span class="token punctuation">(</span>s<span class="token punctuation">.</span><span class="token function">Count</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">		<span class="token keyword">if</span> s<span class="token punctuation">.</span><span class="token function">Set</span><span class="token punctuation">(</span>key<span class="token punctuation">,</span> url<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">			<span class="token keyword">return</span> key</span>
<span class="line">		<span class="token punctuation">}</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line">	<span class="token comment">// shouldn’t get here</span></span>
<span class="line">	<span class="token keyword">return</span> <span class="token string">""</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>for</code> 循环会一直尝试调用 <code v-pre>Set()</code> 直到成功为止（意味着生成了一个尚未存在的短网址）。现在我们定义好了数据存储，以及配套的可工作的函数（见代码 <a href="examples/chapter_19/goto_v1/store.go">store.go</a>）。但这本身并不能完成任务，我们还需要开发 web 服务器以交付 <code v-pre>Add</code> 和 <code v-pre>Redirect</code> 服务。</p>
<h2 id="链接" tabindex="-1"><a class="header-anchor" href="#链接"><span>链接</span></a></h2>
<ul>
<li><RouteLink to="/chapter-4/directory.html">目录</RouteLink></li>
<li>上一节：<RouteLink to="/chapter-4/19.2.html">短网址项目简介</RouteLink></li>
<li>下一节：<RouteLink to="/chapter-4/19.4.html">用户界面：web 服务端</RouteLink></li>
</ul>
</div></template>


