<template><div><h1 id="版本-3-添加协程" tabindex="-1"><a class="header-anchor" href="#版本-3-添加协程"><span>版本 3 - 添加协程</span></a></h1>
<p>第 3 个版本的代码 <em>goto_v3</em> 见 <a href="examples/chapter_19/goto_v3">goto_v3</a>。</p>
<h1 id="_19-6-用协程优化性能" tabindex="-1"><a class="header-anchor" href="#_19-6-用协程优化性能"><span>19.6 用协程优化性能</span></a></h1>
<p>如果有太多客户端同时尝试添加 URL，第 2 个版本依旧存在性能问题。得益于锁机制，我们的 <code v-pre>map</code> 可以在并发访问环境下安全地更新，但每条新产生的记录都要立即写入磁盘，这种机制成为了瓶颈。写入操作可能同时发生，根据不同操作系统的特性，可能会产生数据损坏。就算不产生写入冲突，每个客户端在 <code v-pre>Put()</code> 函数返回前，必须等待数据写入磁盘。因此，在一个 I/O 负载很高的系统中，客户端为了完成 <code v-pre>Add()</code> 请求，将等待更长的不必要的时间。</p>
<p>为缓解该问题，必须对 <code v-pre>Put()</code> 和存储进程<em>解耦</em>：我们将使用 Go 的并发机制。我们不再将记录直接写入磁盘，而是发送到一个<em>通道</em>中，它是某种形式的缓冲区，因而发送函数不必等待它完成。</p>
<p>保存进程会从该通道读取数据并写入磁盘。它是以 <code v-pre>saveLoop()</code> 协程启动的独立线程。现在 <code v-pre>main()</code> 和 <code v-pre>saveLoop()</code> 并行地执行，不会再发生阻塞。</p>
<p>将 <code v-pre>URLStore</code> 的 <code v-pre>file</code> 字段替换为 <code v-pre>record</code> 类型的通道：<code v-pre>save chan record</code>。</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token keyword">type</span> URLStore <span class="token keyword">struct</span> <span class="token punctuation">{</span></span>
<span class="line">	urls <span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span><span class="token builtin">string</span></span>
<span class="line">	mu sync<span class="token punctuation">.</span>RWMutex</span>
<span class="line">	save <span class="token keyword">chan</span> record</span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>通道和 <code v-pre>map</code> 一样，必须用 <code v-pre>make()</code> 创建。我们会以此修改 <code v-pre>NewURLStore()</code> 工厂函数，并给定缓冲区大小为 1000，例如：<code v-pre>save := make(chan record, saveQueueLength)</code>。为解决性能问题，<code v-pre>Put</code> 可以发送记录 <code v-pre>record</code> 到带缓冲的 <code v-pre>save</code> 通道：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token keyword">func</span> <span class="token punctuation">(</span>s <span class="token operator">*</span>URLStore<span class="token punctuation">)</span> <span class="token function">Put</span><span class="token punctuation">(</span>url <span class="token builtin">string</span><span class="token punctuation">)</span> <span class="token builtin">string</span> <span class="token punctuation">{</span></span>
<span class="line">	<span class="token keyword">for</span> <span class="token punctuation">{</span></span>
<span class="line">		key <span class="token operator">:=</span> <span class="token function">genKey</span><span class="token punctuation">(</span>s<span class="token punctuation">.</span><span class="token function">Count</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">		<span class="token keyword">if</span> s<span class="token punctuation">.</span><span class="token function">Set</span><span class="token punctuation">(</span>key<span class="token punctuation">,</span> url<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">			s<span class="token punctuation">.</span>save <span class="token operator">&lt;-</span> record<span class="token punctuation">{</span>key<span class="token punctuation">,</span> url<span class="token punctuation">}</span></span>
<span class="line">			<span class="token keyword">return</span> key</span>
<span class="line">		<span class="token punctuation">}</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line">	<span class="token function">panic</span><span class="token punctuation">(</span><span class="token string">"shouldn't get here"</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>save</code> 通道的另一端必须有一个接收者：新的 <code v-pre>saveLoop()</code> 方法在独立的协程中运行，它接收 <code v-pre>record</code> 值并将它们写入到文件。<code v-pre>saveLoop()</code> 是在 <code v-pre>NewURLStore()</code> 函数中用 <code v-pre>go</code> 关键字启动的。现在，可以移除不必要的打开文件的代码。以下是修改后的 <code v-pre>NewURLStore()</code>：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token keyword">const</span> saveQueueLength <span class="token operator">=</span> <span class="token number">1000</span></span>
<span class="line"><span class="token keyword">func</span> <span class="token function">NewURLStore</span><span class="token punctuation">(</span>filename <span class="token builtin">string</span><span class="token punctuation">)</span> <span class="token operator">*</span>URLStore <span class="token punctuation">{</span></span>
<span class="line">	s <span class="token operator">:=</span> <span class="token operator">&amp;</span>URLStore<span class="token punctuation">{</span></span>
<span class="line">		urls<span class="token punctuation">:</span> <span class="token function">make</span><span class="token punctuation">(</span><span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span><span class="token builtin">string</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">		save<span class="token punctuation">:</span> <span class="token function">make</span><span class="token punctuation">(</span><span class="token keyword">chan</span> record<span class="token punctuation">,</span> saveQueueLength<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line">	<span class="token keyword">if</span> err <span class="token operator">:=</span> s<span class="token punctuation">.</span><span class="token function">load</span><span class="token punctuation">(</span>filename<span class="token punctuation">)</span><span class="token punctuation">;</span> err <span class="token operator">!=</span> <span class="token boolean">nil</span> <span class="token punctuation">{</span></span>
<span class="line">		log<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"Error loading URLStore:"</span><span class="token punctuation">,</span> err<span class="token punctuation">)</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line">	<span class="token keyword">go</span> s<span class="token punctuation">.</span><span class="token function">saveLoop</span><span class="token punctuation">(</span>filename<span class="token punctuation">)</span></span>
<span class="line">	<span class="token keyword">return</span> s</span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>以下是 <code v-pre>saveLoop()</code> 方法的代码：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token keyword">func</span> <span class="token punctuation">(</span>s <span class="token operator">*</span>URLStore<span class="token punctuation">)</span> <span class="token function">saveLoop</span><span class="token punctuation">(</span>filename <span class="token builtin">string</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">	f<span class="token punctuation">,</span> err <span class="token operator">:=</span> os<span class="token punctuation">.</span><span class="token function">Open</span><span class="token punctuation">(</span>filename<span class="token punctuation">,</span> os<span class="token punctuation">.</span>O_WRONLY<span class="token operator">|</span>os<span class="token punctuation">.</span>O_CREATE<span class="token operator">|</span>os<span class="token punctuation">.</span>O_APPEND<span class="token punctuation">,</span> <span class="token number">0644</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token keyword">if</span> err <span class="token operator">!=</span> <span class="token boolean">nil</span> <span class="token punctuation">{</span></span>
<span class="line">		log<span class="token punctuation">.</span><span class="token function">Fatal</span><span class="token punctuation">(</span><span class="token string">"URLStore:"</span><span class="token punctuation">,</span> err<span class="token punctuation">)</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line">	<span class="token keyword">defer</span> f<span class="token punctuation">.</span><span class="token function">Close</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">	e <span class="token operator">:=</span> gob<span class="token punctuation">.</span><span class="token function">NewEncoder</span><span class="token punctuation">(</span>f<span class="token punctuation">)</span></span>
<span class="line">	<span class="token keyword">for</span> <span class="token punctuation">{</span></span>
<span class="line">		<span class="token comment">// taking a record from the channel and encoding it</span></span>
<span class="line">		r <span class="token operator">:=</span> <span class="token operator">&lt;-</span>s<span class="token punctuation">.</span>save</span>
<span class="line">		<span class="token keyword">if</span> err <span class="token operator">:=</span> e<span class="token punctuation">.</span><span class="token function">Encode</span><span class="token punctuation">(</span>r<span class="token punctuation">)</span><span class="token punctuation">;</span> err <span class="token operator">!=</span> <span class="token boolean">nil</span> <span class="token punctuation">{</span></span>
<span class="line">			log<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"URLStore:"</span><span class="token punctuation">,</span> err<span class="token punctuation">)</span></span>
<span class="line">		<span class="token punctuation">}</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>在无限循环中，记录从 <code v-pre>save</code> 通道读取，然后编码到文件中。</p>
<p>我们在 <RouteLink to="/chapter-4/14.0.html">14 章</RouteLink> 深入学习了协程和通道，但在这里我们见到了实用的案例，更好地管理程序的不同部分。注意现在 <code v-pre>Encoder</code> 对象只被创建一次，而不是每次保存时都创建，这也可以节省了一些内存和运算处理。</p>
<p>还有一个改进可以使 goto 更灵活：我们可以将文件名、监听地址和主机名定义为标志 (flag)，来代替在程序中硬编码或定义常量。这样当程序启动时，可以在命令行中指定它们的新值，如果没有指定，将采用 flag 的默认值。该功能来自另一个包，所以需要 <code v-pre>import &quot;flag&quot;</code>（这个包的更详细信息见 <RouteLink to="/chapter-4/12.4.html">12.4 节</RouteLink>）。</p>
<p>先创建一些全局变量来保存 flag 的值：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token keyword">var</span> <span class="token punctuation">(</span></span>
<span class="line">	listenAddr <span class="token operator">=</span> flag<span class="token punctuation">.</span><span class="token function">String</span><span class="token punctuation">(</span><span class="token string">"http"</span><span class="token punctuation">,</span> <span class="token string">":8080"</span><span class="token punctuation">,</span> <span class="token string">"http listen address"</span><span class="token punctuation">)</span></span>
<span class="line">	dataFile <span class="token operator">=</span> flag<span class="token punctuation">.</span><span class="token function">String</span><span class="token punctuation">(</span><span class="token string">"file"</span><span class="token punctuation">,</span> <span class="token string">"store.gob"</span><span class="token punctuation">,</span> <span class="token string">"data store file name"</span><span class="token punctuation">)</span></span>
<span class="line">	hostname <span class="token operator">=</span> flag<span class="token punctuation">.</span><span class="token function">String</span><span class="token punctuation">(</span><span class="token string">"host"</span><span class="token punctuation">,</span> <span class="token string">"localhost:8080"</span><span class="token punctuation">,</span> <span class="token string">"host name and port"</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>为了处理命令行参数，必须把 <code v-pre>flag.Parse()</code> 添加到 <code v-pre>main()</code> 函数中，在 flag 解析后才能实例化 <code v-pre>URLStore</code>，一旦得知了 <code v-pre>dataFile</code> 的值（在代码中使用了 <code v-pre>*dataFile</code>，因为 flag 是指针类型必须解除引用来获取值，见 <RouteLink to="/chapter-4/04.9.html">4.9 节</RouteLink>）：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token keyword">var</span> store <span class="token operator">*</span>URLStore</span>
<span class="line"><span class="token keyword">func</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">	flag<span class="token punctuation">.</span><span class="token function">Parse</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">	store <span class="token operator">=</span> <span class="token function">NewURLStore</span><span class="token punctuation">(</span><span class="token operator">*</span>dataFile<span class="token punctuation">)</span></span>
<span class="line">	http<span class="token punctuation">.</span><span class="token function">HandleFunc</span><span class="token punctuation">(</span><span class="token string">"/"</span><span class="token punctuation">,</span> Redirect<span class="token punctuation">)</span></span>
<span class="line">	http<span class="token punctuation">.</span><span class="token function">HandleFunc</span><span class="token punctuation">(</span><span class="token string">"/add"</span><span class="token punctuation">,</span> Add<span class="token punctuation">)</span></span>
<span class="line">	http<span class="token punctuation">.</span><span class="token function">ListenAndServe</span><span class="token punctuation">(</span><span class="token operator">*</span>listenAddr<span class="token punctuation">,</span> <span class="token boolean">nil</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>现在 <code v-pre>Add()</code> 处理函数中须用 <code v-pre>*hostname</code> 替换 <code v-pre>localhost:8080</code>：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line">fmt<span class="token punctuation">.</span><span class="token function">Fprintf</span><span class="token punctuation">(</span>w<span class="token punctuation">,</span> <span class="token string">"http://%s/%s"</span><span class="token punctuation">,</span> <span class="token operator">*</span>hostname<span class="token punctuation">,</span> key<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>编译或直接使用现有的可执行程序测试第 3 个版本。</p>
<h2 id="链接" tabindex="-1"><a class="header-anchor" href="#链接"><span>链接</span></a></h2>
<ul>
<li><RouteLink to="/chapter-4/directory.html">目录</RouteLink></li>
<li>上一节：<RouteLink to="/chapter-4/19.5.html">持久化存储：gob</RouteLink></li>
<li>下一节：<RouteLink to="/chapter-4/19.7.html">以 json 格式存储</RouteLink></li>
</ul>
</div></template>


