<template><div><h1 id="_8-5-map-的排序" tabindex="-1"><a class="header-anchor" href="#_8-5-map-的排序"><span>8.5 map 的排序</span></a></h1>
<p><code v-pre>map</code> 默认是无序的，不管是按照 key 还是按照 value 默认都不排序（详见第 8.3 节）。</p>
<p>如果你想为 <code v-pre>map</code> 排序，需要将 key（或者 value）拷贝到一个切片，再对切片排序（使用 <code v-pre>sort</code> 包，详见<RouteLink to="/chapter-2/07.6.html">第 7.6.6 节</RouteLink>），然后可以使用切片的 for-range 方法打印出所有的 key 和 value。</p>
<p>下面有一个示例：</p>
<p>示例 8.6 <a href="examples/chapter_8/sort_map.go">sort_map.go</a>：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token comment">// the telephone alphabet:</span></span>
<span class="line"><span class="token keyword">package</span> main</span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">(</span></span>
<span class="line">	<span class="token string">"fmt"</span></span>
<span class="line">	<span class="token string">"sort"</span></span>
<span class="line"><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">var</span> <span class="token punctuation">(</span></span>
<span class="line">	barVal <span class="token operator">=</span> <span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span><span class="token builtin">int</span><span class="token punctuation">{</span><span class="token string">"alpha"</span><span class="token punctuation">:</span> <span class="token number">34</span><span class="token punctuation">,</span> <span class="token string">"bravo"</span><span class="token punctuation">:</span> <span class="token number">56</span><span class="token punctuation">,</span> <span class="token string">"charlie"</span><span class="token punctuation">:</span> <span class="token number">23</span><span class="token punctuation">,</span></span>
<span class="line">							<span class="token string">"delta"</span><span class="token punctuation">:</span> <span class="token number">87</span><span class="token punctuation">,</span> <span class="token string">"echo"</span><span class="token punctuation">:</span> <span class="token number">56</span><span class="token punctuation">,</span> <span class="token string">"foxtrot"</span><span class="token punctuation">:</span> <span class="token number">12</span><span class="token punctuation">,</span></span>
<span class="line">							<span class="token string">"golf"</span><span class="token punctuation">:</span> <span class="token number">34</span><span class="token punctuation">,</span> <span class="token string">"hotel"</span><span class="token punctuation">:</span> <span class="token number">16</span><span class="token punctuation">,</span> <span class="token string">"indio"</span><span class="token punctuation">:</span> <span class="token number">87</span><span class="token punctuation">,</span></span>
<span class="line">							<span class="token string">"juliet"</span><span class="token punctuation">:</span> <span class="token number">65</span><span class="token punctuation">,</span> <span class="token string">"kili"</span><span class="token punctuation">:</span> <span class="token number">43</span><span class="token punctuation">,</span> <span class="token string">"lima"</span><span class="token punctuation">:</span> <span class="token number">98</span><span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">func</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">	fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"unsorted:"</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token keyword">for</span> k<span class="token punctuation">,</span> v <span class="token operator">:=</span> <span class="token keyword">range</span> barVal <span class="token punctuation">{</span></span>
<span class="line">		fmt<span class="token punctuation">.</span><span class="token function">Printf</span><span class="token punctuation">(</span><span class="token string">"Key: %v, Value: %v / "</span><span class="token punctuation">,</span> k<span class="token punctuation">,</span> v<span class="token punctuation">)</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line">	keys <span class="token operator">:=</span> <span class="token function">make</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token builtin">string</span><span class="token punctuation">,</span> <span class="token function">len</span><span class="token punctuation">(</span>barVal<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">	i <span class="token operator">:=</span> <span class="token number">0</span></span>
<span class="line">	<span class="token keyword">for</span> k<span class="token punctuation">,</span> <span class="token boolean">_</span> <span class="token operator">:=</span> <span class="token keyword">range</span> barVal <span class="token punctuation">{</span></span>
<span class="line">		keys<span class="token punctuation">[</span>i<span class="token punctuation">]</span> <span class="token operator">=</span> k</span>
<span class="line">		i<span class="token operator">++</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line">	sort<span class="token punctuation">.</span><span class="token function">Strings</span><span class="token punctuation">(</span>keys<span class="token punctuation">)</span></span>
<span class="line">	fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">	fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"sorted:"</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token keyword">for</span> <span class="token boolean">_</span><span class="token punctuation">,</span> k <span class="token operator">:=</span> <span class="token keyword">range</span> keys <span class="token punctuation">{</span></span>
<span class="line">		fmt<span class="token punctuation">.</span><span class="token function">Printf</span><span class="token punctuation">(</span><span class="token string">"Key: %v, Value: %v / "</span><span class="token punctuation">,</span> k<span class="token punctuation">,</span> barVal<span class="token punctuation">[</span>k<span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>输出结果：</p>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh" data-title="sh"><pre v-pre><code><span class="line">	unsorted:</span>
<span class="line">	Key: bravo, Value: <span class="token number">56</span> / Key: echo, Value: <span class="token number">56</span> / Key: indio, Value: <span class="token number">87</span> / Key: juliet, Value: <span class="token number">65</span> / Key: alpha, Value: <span class="token number">34</span> / Key: charlie, Value: <span class="token number">23</span> / Key: delta, Value: <span class="token number">87</span> / Key: foxtrot, Value: <span class="token number">12</span> / Key: golf, Value: <span class="token number">34</span> / Key: hotel, Value: <span class="token number">16</span> / Key: kili, Value: <span class="token number">43</span> / Key: lima, Value: <span class="token number">98</span> /</span>
<span class="line">	sorted:</span>
<span class="line">	Key: alpha, Value: <span class="token number">34</span> / Key: bravo, Value: <span class="token number">56</span> / Key: charlie, Value: <span class="token number">23</span> / Key: delta, Value: <span class="token number">87</span> / Key: echo, Value: <span class="token number">56</span> / Key: foxtrot, Value: <span class="token number">12</span> / Key: golf, Value: <span class="token number">34</span> / Key: hotel, Value: <span class="token number">16</span> / Key: indio, Value: <span class="token number">87</span> / Key: juliet, Value: <span class="token number">65</span> / Key: kili, Value: <span class="token number">43</span> / Key: lima, Value: <span class="token number">98</span> /</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>但是如果你想要一个排序的列表，那么最好使用结构体切片，这样会更有效：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token keyword">type</span> name <span class="token keyword">struct</span> <span class="token punctuation">{</span></span>
<span class="line">	key <span class="token builtin">string</span></span>
<span class="line">	value <span class="token builtin">int</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


