<template><div><h1 id="_8-6-将-map-的键值对调" tabindex="-1"><a class="header-anchor" href="#_8-6-将-map-的键值对调"><span>8.6 将 map 的键值对调</span></a></h1>
<p>这里对调是指调换 key 和 value。如果 <code v-pre>map</code> 的值类型可以作为 key 且所有的 value 是唯一的，那么通过下面的方法可以简单的做到键值对调。</p>
<p>示例 8.7 <a href="examples/chapter_8/invert_map.go">invert_map.go</a>：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token keyword">package</span> main</span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">(</span></span>
<span class="line">	<span class="token string">"fmt"</span></span>
<span class="line"><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">var</span> <span class="token punctuation">(</span></span>
<span class="line">	barVal <span class="token operator">=</span> <span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span><span class="token builtin">int</span><span class="token punctuation">{</span><span class="token string">"alpha"</span><span class="token punctuation">:</span> <span class="token number">34</span><span class="token punctuation">,</span> <span class="token string">"bravo"</span><span class="token punctuation">:</span> <span class="token number">56</span><span class="token punctuation">,</span> <span class="token string">"charlie"</span><span class="token punctuation">:</span> <span class="token number">23</span><span class="token punctuation">,</span></span>
<span class="line">							<span class="token string">"delta"</span><span class="token punctuation">:</span> <span class="token number">87</span><span class="token punctuation">,</span> <span class="token string">"echo"</span><span class="token punctuation">:</span> <span class="token number">56</span><span class="token punctuation">,</span> <span class="token string">"foxtrot"</span><span class="token punctuation">:</span> <span class="token number">12</span><span class="token punctuation">,</span></span>
<span class="line">							<span class="token string">"golf"</span><span class="token punctuation">:</span> <span class="token number">34</span><span class="token punctuation">,</span> <span class="token string">"hotel"</span><span class="token punctuation">:</span> <span class="token number">16</span><span class="token punctuation">,</span> <span class="token string">"indio"</span><span class="token punctuation">:</span> <span class="token number">87</span><span class="token punctuation">,</span></span>
<span class="line">							<span class="token string">"juliet"</span><span class="token punctuation">:</span> <span class="token number">65</span><span class="token punctuation">,</span> <span class="token string">"kili"</span><span class="token punctuation">:</span> <span class="token number">43</span><span class="token punctuation">,</span> <span class="token string">"lima"</span><span class="token punctuation">:</span> <span class="token number">98</span><span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">func</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">	invMap <span class="token operator">:=</span> <span class="token function">make</span><span class="token punctuation">(</span><span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">int</span><span class="token punctuation">]</span><span class="token builtin">string</span><span class="token punctuation">,</span> <span class="token function">len</span><span class="token punctuation">(</span>barVal<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token keyword">for</span> k<span class="token punctuation">,</span> v <span class="token operator">:=</span> <span class="token keyword">range</span> barVal <span class="token punctuation">{</span></span>
<span class="line">		invMap<span class="token punctuation">[</span>v<span class="token punctuation">]</span> <span class="token operator">=</span> k</span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line">	fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"inverted:"</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token keyword">for</span> k<span class="token punctuation">,</span> v <span class="token operator">:=</span> <span class="token keyword">range</span> invMap <span class="token punctuation">{</span></span>
<span class="line">		fmt<span class="token punctuation">.</span><span class="token function">Printf</span><span class="token punctuation">(</span><span class="token string">"Key: %v, Value: %v / "</span><span class="token punctuation">,</span> k<span class="token punctuation">,</span> v<span class="token punctuation">)</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>输出结果：</p>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh" data-title="sh"><pre v-pre><code><span class="line">inverted:</span>
<span class="line">Key: <span class="token number">34</span>, Value: golf / Key: <span class="token number">23</span>, Value: charlie / Key: <span class="token number">16</span>, Value: hotel / Key: <span class="token number">87</span>, Value: delta / Key: <span class="token number">98</span>, Value: lima / Key: <span class="token number">12</span>, Value: foxtrot / Key: <span class="token number">43</span>, Value: kili / Key: <span class="token number">56</span>, Value: bravo / Key: <span class="token number">65</span>, Value: juliet /</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><p>如果原始 value 值不唯一那这么做肯定会出问题；这种情况下不会报错，但是当遇到不唯一的 key 时应当直接停止对调，且此时对调后的 <code v-pre>map</code> 很可能没有包含原 <code v-pre>map</code> 的所有键值对！一种解决方法就是仔细检查唯一性并且使用多值 <code v-pre>map</code>，比如使用 <code v-pre>map[int][]string</code> 类型。</p>
<p><strong>练习 8.2</strong> <a href="exercises/chapter_8/map_drinks.go">map_drinks.go</a></p>
<p>构造一个将英文饮料名映射为法语（或者任意你的母语）的集合；先打印所有的饮料，然后打印原名和翻译后的名字。接下来按照英文名排序后再打印出来。</p>
</div></template>


