<template><div><h1 id="_11-14-结构体、集合和高阶函数" tabindex="-1"><a class="header-anchor" href="#_11-14-结构体、集合和高阶函数"><span>11.14 结构体、集合和高阶函数</span></a></h1>
<p>通常你在应用中定义了一个结构体，那么你也可能需要这个结构体的（指针）对象集合，比如：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token keyword">type</span> Any <span class="token keyword">interface</span><span class="token punctuation">{</span><span class="token punctuation">}</span></span>
<span class="line"><span class="token keyword">type</span> Car <span class="token keyword">struct</span> <span class="token punctuation">{</span></span>
<span class="line">	Model        <span class="token builtin">string</span></span>
<span class="line">	Manufacturer <span class="token builtin">string</span></span>
<span class="line">	BuildYear    <span class="token builtin">int</span></span>
<span class="line">	<span class="token comment">// ...</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">type</span> Cars <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token operator">*</span>Car</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>然后我们就可以使用高阶函数，实际上也就是把函数作为定义所需方法（其他函数）的参数，例如：</p>
<p>1）定义一个通用的 <code v-pre>Process()</code> 函数，它接收一个作用于每一辆 car 的 f 函数作参数：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token comment">// Process all cars with the given function f:</span></span>
<span class="line"><span class="token keyword">func</span> <span class="token punctuation">(</span>cs Cars<span class="token punctuation">)</span> <span class="token function">Process</span><span class="token punctuation">(</span>f <span class="token keyword">func</span><span class="token punctuation">(</span>car <span class="token operator">*</span>Car<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">	<span class="token keyword">for</span> <span class="token boolean">_</span><span class="token punctuation">,</span> c <span class="token operator">:=</span> <span class="token keyword">range</span> cs <span class="token punctuation">{</span></span>
<span class="line">		<span class="token function">f</span><span class="token punctuation">(</span>c<span class="token punctuation">)</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>2）在上面的基础上，实现一个查找函数来获取子集合，并在 <code v-pre>Process()</code> 中传入一个闭包执行（这样就可以访问局部切片 <code v-pre>cars</code>）：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token comment">// Find all cars matching a given criteria.</span></span>
<span class="line"><span class="token keyword">func</span> <span class="token punctuation">(</span>cs Cars<span class="token punctuation">)</span> <span class="token function">FindAll</span><span class="token punctuation">(</span>f <span class="token keyword">func</span><span class="token punctuation">(</span>car <span class="token operator">*</span>Car<span class="token punctuation">)</span> <span class="token builtin">bool</span><span class="token punctuation">)</span> Cars <span class="token punctuation">{</span></span>
<span class="line"></span>
<span class="line">	cars <span class="token operator">:=</span> <span class="token function">make</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token operator">*</span>Car<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span></span>
<span class="line">	cs<span class="token punctuation">.</span><span class="token function">Process</span><span class="token punctuation">(</span><span class="token keyword">func</span><span class="token punctuation">(</span>c <span class="token operator">*</span>Car<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">		<span class="token keyword">if</span> <span class="token function">f</span><span class="token punctuation">(</span>c<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">			cars <span class="token operator">=</span> <span class="token function">append</span><span class="token punctuation">(</span>cars<span class="token punctuation">,</span> c<span class="token punctuation">)</span></span>
<span class="line">		<span class="token punctuation">}</span></span>
<span class="line">	<span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token keyword">return</span> cars</span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>3）实现对应作用的功效 (Map-functionality)，从每个 <code v-pre>car</code> 对象当中产出某些东西：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token comment">// Process cars and create new data.</span></span>
<span class="line"><span class="token keyword">func</span> <span class="token punctuation">(</span>cs Cars<span class="token punctuation">)</span> <span class="token function">Map</span><span class="token punctuation">(</span>f <span class="token keyword">func</span><span class="token punctuation">(</span>car <span class="token operator">*</span>Car<span class="token punctuation">)</span> Any<span class="token punctuation">)</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>Any <span class="token punctuation">{</span></span>
<span class="line">	result <span class="token operator">:=</span> <span class="token function">make</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span>Any<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span></span>
<span class="line">	ix <span class="token operator">:=</span> <span class="token number">0</span></span>
<span class="line">	cs<span class="token punctuation">.</span><span class="token function">Process</span><span class="token punctuation">(</span><span class="token keyword">func</span><span class="token punctuation">(</span>c <span class="token operator">*</span>Car<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">		result<span class="token punctuation">[</span>ix<span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token function">f</span><span class="token punctuation">(</span>c<span class="token punctuation">)</span></span>
<span class="line">		ix<span class="token operator">++</span></span>
<span class="line">	<span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token keyword">return</span> result</span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>现在我们可以定义下面这样的具体查询：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line">allNewBMWs <span class="token operator">:=</span> allCars<span class="token punctuation">.</span><span class="token function">FindAll</span><span class="token punctuation">(</span><span class="token keyword">func</span><span class="token punctuation">(</span>car <span class="token operator">*</span>Car<span class="token punctuation">)</span> <span class="token builtin">bool</span> <span class="token punctuation">{</span></span>
<span class="line">	<span class="token keyword">return</span> <span class="token punctuation">(</span>car<span class="token punctuation">.</span>Manufacturer <span class="token operator">==</span> <span class="token string">"BMW"</span><span class="token punctuation">)</span> <span class="token operator">&amp;&amp;</span> <span class="token punctuation">(</span>car<span class="token punctuation">.</span>BuildYear <span class="token operator">></span> <span class="token number">2010</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>4）我们也可以根据参数返回不同的函数。也许我们想根据不同的厂商添加汽车到不同的集合，但是这（这种映射关系）可能会是会改变的。所以我们可以定义一个函数来产生特定的添加函数和 <code v-pre>map</code> 集：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token keyword">func</span> <span class="token function">MakeSortedAppender</span><span class="token punctuation">(</span>manufacturers <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token builtin">string</span><span class="token punctuation">)</span><span class="token punctuation">(</span><span class="token keyword">func</span><span class="token punctuation">(</span>car <span class="token operator">*</span>Car<span class="token punctuation">)</span><span class="token punctuation">,</span><span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span>Cars<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">	<span class="token comment">// Prepare maps of sorted cars.</span></span>
<span class="line">	sortedCars <span class="token operator">:=</span> <span class="token function">make</span><span class="token punctuation">(</span><span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span>Cars<span class="token punctuation">)</span></span>
<span class="line">	<span class="token keyword">for</span> <span class="token boolean">_</span><span class="token punctuation">,</span> m <span class="token operator">:=</span> <span class="token keyword">range</span> manufacturers <span class="token punctuation">{</span></span>
<span class="line">		sortedCars<span class="token punctuation">[</span>m<span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token function">make</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token operator">*</span>Car<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line">	sortedCars<span class="token punctuation">[</span><span class="token string">"Default"</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token function">make</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token operator">*</span>Car<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token comment">// Prepare appender function:</span></span>
<span class="line">	appender <span class="token operator">:=</span> <span class="token keyword">func</span><span class="token punctuation">(</span>c <span class="token operator">*</span>Car<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">		<span class="token keyword">if</span> <span class="token boolean">_</span><span class="token punctuation">,</span> ok <span class="token operator">:=</span> sortedCars<span class="token punctuation">[</span>c<span class="token punctuation">.</span>Manufacturer<span class="token punctuation">]</span><span class="token punctuation">;</span> ok <span class="token punctuation">{</span></span>
<span class="line">			sortedCars<span class="token punctuation">[</span>c<span class="token punctuation">.</span>Manufacturer<span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token function">append</span><span class="token punctuation">(</span>sortedCars<span class="token punctuation">[</span>c<span class="token punctuation">.</span>Manufacturer<span class="token punctuation">]</span><span class="token punctuation">,</span> c<span class="token punctuation">)</span></span>
<span class="line">		<span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span></span>
<span class="line">			sortedCars<span class="token punctuation">[</span><span class="token string">"Default"</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token function">append</span><span class="token punctuation">(</span>sortedCars<span class="token punctuation">[</span><span class="token string">"Default"</span><span class="token punctuation">]</span><span class="token punctuation">,</span> c<span class="token punctuation">)</span></span>
<span class="line">		<span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line">	<span class="token keyword">return</span> appender<span class="token punctuation">,</span> sortedCars</span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>现在我们可以用它把汽车分类为独立的集合，像这样：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line">manufacturers <span class="token operator">:=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token builtin">string</span><span class="token punctuation">{</span><span class="token string">"Ford"</span><span class="token punctuation">,</span> <span class="token string">"Aston Martin"</span><span class="token punctuation">,</span> <span class="token string">"Land Rover"</span><span class="token punctuation">,</span> <span class="token string">"BMW"</span><span class="token punctuation">,</span> <span class="token string">"Jaguar"</span><span class="token punctuation">}</span></span>
<span class="line">sortedAppender<span class="token punctuation">,</span> sortedCars <span class="token operator">:=</span> <span class="token function">MakeSortedAppender</span><span class="token punctuation">(</span>manufacturers<span class="token punctuation">)</span></span>
<span class="line">allUnsortedCars<span class="token punctuation">.</span><span class="token function">Process</span><span class="token punctuation">(</span>sortedAppender<span class="token punctuation">)</span></span>
<span class="line">BMWCount <span class="token operator">:=</span> <span class="token function">len</span><span class="token punctuation">(</span>sortedCars<span class="token punctuation">[</span><span class="token string">"BMW"</span><span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们让这些代码在下面的程序 cars.go 中执行：</p>
<p>示例 11.18 <a href="examples/chapter_11/cars.go">cars.go</a>：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token comment">// cars.go</span></span>
<span class="line"><span class="token keyword">package</span> main</span>
<span class="line"></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">(</span></span>
<span class="line">	<span class="token string">"fmt"</span></span>
<span class="line"><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">type</span> Any <span class="token keyword">interface</span><span class="token punctuation">{</span><span class="token punctuation">}</span></span>
<span class="line"><span class="token keyword">type</span> Car <span class="token keyword">struct</span> <span class="token punctuation">{</span></span>
<span class="line">	Model        <span class="token builtin">string</span></span>
<span class="line">	Manufacturer <span class="token builtin">string</span></span>
<span class="line">	BuildYear    <span class="token builtin">int</span></span>
<span class="line">	<span class="token comment">// ...</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"><span class="token keyword">type</span> Cars <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token operator">*</span>Car</span>
<span class="line"></span>
<span class="line"><span class="token keyword">func</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">	<span class="token comment">// make some cars:</span></span>
<span class="line">	ford <span class="token operator">:=</span> <span class="token operator">&amp;</span>Car<span class="token punctuation">{</span><span class="token string">"Fiesta"</span><span class="token punctuation">,</span> <span class="token string">"Ford"</span><span class="token punctuation">,</span> <span class="token number">2008</span><span class="token punctuation">}</span></span>
<span class="line">	bmw <span class="token operator">:=</span> <span class="token operator">&amp;</span>Car<span class="token punctuation">{</span><span class="token string">"XL 450"</span><span class="token punctuation">,</span> <span class="token string">"BMW"</span><span class="token punctuation">,</span> <span class="token number">2011</span><span class="token punctuation">}</span></span>
<span class="line">	merc <span class="token operator">:=</span> <span class="token operator">&amp;</span>Car<span class="token punctuation">{</span><span class="token string">"D600"</span><span class="token punctuation">,</span> <span class="token string">"Mercedes"</span><span class="token punctuation">,</span> <span class="token number">2009</span><span class="token punctuation">}</span></span>
<span class="line">	bmw2 <span class="token operator">:=</span> <span class="token operator">&amp;</span>Car<span class="token punctuation">{</span><span class="token string">"X 800"</span><span class="token punctuation">,</span> <span class="token string">"BMW"</span><span class="token punctuation">,</span> <span class="token number">2008</span><span class="token punctuation">}</span></span>
<span class="line">	<span class="token comment">// query:</span></span>
<span class="line">	allCars <span class="token operator">:=</span> <span class="token function">Cars</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token operator">*</span>Car<span class="token punctuation">{</span>ford<span class="token punctuation">,</span> bmw<span class="token punctuation">,</span> merc<span class="token punctuation">,</span> bmw2<span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line">	allNewBMWs <span class="token operator">:=</span> allCars<span class="token punctuation">.</span><span class="token function">FindAll</span><span class="token punctuation">(</span><span class="token keyword">func</span><span class="token punctuation">(</span>car <span class="token operator">*</span>Car<span class="token punctuation">)</span> <span class="token builtin">bool</span> <span class="token punctuation">{</span></span>
<span class="line">		<span class="token keyword">return</span> <span class="token punctuation">(</span>car<span class="token punctuation">.</span>Manufacturer <span class="token operator">==</span> <span class="token string">"BMW"</span><span class="token punctuation">)</span> <span class="token operator">&amp;&amp;</span> <span class="token punctuation">(</span>car<span class="token punctuation">.</span>BuildYear <span class="token operator">></span> <span class="token number">2010</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line">	fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"AllCars: "</span><span class="token punctuation">,</span> allCars<span class="token punctuation">)</span></span>
<span class="line">	fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"New BMWs: "</span><span class="token punctuation">,</span> allNewBMWs<span class="token punctuation">)</span></span>
<span class="line">	<span class="token comment">//</span></span>
<span class="line">	manufacturers <span class="token operator">:=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token builtin">string</span><span class="token punctuation">{</span><span class="token string">"Ford"</span><span class="token punctuation">,</span> <span class="token string">"Aston Martin"</span><span class="token punctuation">,</span> <span class="token string">"Land Rover"</span><span class="token punctuation">,</span> <span class="token string">"BMW"</span><span class="token punctuation">,</span> <span class="token string">"Jaguar"</span><span class="token punctuation">}</span></span>
<span class="line">	sortedAppender<span class="token punctuation">,</span> sortedCars <span class="token operator">:=</span> <span class="token function">MakeSortedAppender</span><span class="token punctuation">(</span>manufacturers<span class="token punctuation">)</span></span>
<span class="line">	allCars<span class="token punctuation">.</span><span class="token function">Process</span><span class="token punctuation">(</span>sortedAppender<span class="token punctuation">)</span></span>
<span class="line">	fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"Map sortedCars: "</span><span class="token punctuation">,</span> sortedCars<span class="token punctuation">)</span></span>
<span class="line">	BMWCount <span class="token operator">:=</span> <span class="token function">len</span><span class="token punctuation">(</span>sortedCars<span class="token punctuation">[</span><span class="token string">"BMW"</span><span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line">	fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"We have "</span><span class="token punctuation">,</span> BMWCount<span class="token punctuation">,</span> <span class="token string">" BMWs"</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Process all cars with the given function f:</span></span>
<span class="line"><span class="token keyword">func</span> <span class="token punctuation">(</span>cs Cars<span class="token punctuation">)</span> <span class="token function">Process</span><span class="token punctuation">(</span>f <span class="token keyword">func</span><span class="token punctuation">(</span>car <span class="token operator">*</span>Car<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">	<span class="token keyword">for</span> <span class="token boolean">_</span><span class="token punctuation">,</span> c <span class="token operator">:=</span> <span class="token keyword">range</span> cs <span class="token punctuation">{</span></span>
<span class="line">		<span class="token function">f</span><span class="token punctuation">(</span>c<span class="token punctuation">)</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Find all cars matching a given criteria.</span></span>
<span class="line"><span class="token keyword">func</span> <span class="token punctuation">(</span>cs Cars<span class="token punctuation">)</span> <span class="token function">FindAll</span><span class="token punctuation">(</span>f <span class="token keyword">func</span><span class="token punctuation">(</span>car <span class="token operator">*</span>Car<span class="token punctuation">)</span> <span class="token builtin">bool</span><span class="token punctuation">)</span> Cars <span class="token punctuation">{</span></span>
<span class="line">	cars <span class="token operator">:=</span> <span class="token function">make</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token operator">*</span>Car<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">	cs<span class="token punctuation">.</span><span class="token function">Process</span><span class="token punctuation">(</span><span class="token keyword">func</span><span class="token punctuation">(</span>c <span class="token operator">*</span>Car<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">		<span class="token keyword">if</span> <span class="token function">f</span><span class="token punctuation">(</span>c<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">			cars <span class="token operator">=</span> <span class="token function">append</span><span class="token punctuation">(</span>cars<span class="token punctuation">,</span> c<span class="token punctuation">)</span></span>
<span class="line">		<span class="token punctuation">}</span></span>
<span class="line">	<span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token keyword">return</span> cars</span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Process cars and create new data.</span></span>
<span class="line"><span class="token keyword">func</span> <span class="token punctuation">(</span>cs Cars<span class="token punctuation">)</span> <span class="token function">Map</span><span class="token punctuation">(</span>f <span class="token keyword">func</span><span class="token punctuation">(</span>car <span class="token operator">*</span>Car<span class="token punctuation">)</span> Any<span class="token punctuation">)</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>Any <span class="token punctuation">{</span></span>
<span class="line">	result <span class="token operator">:=</span> <span class="token function">make</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span>Any<span class="token punctuation">,</span> <span class="token function">len</span><span class="token punctuation">(</span>cs<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">	ix <span class="token operator">:=</span> <span class="token number">0</span></span>
<span class="line">	cs<span class="token punctuation">.</span><span class="token function">Process</span><span class="token punctuation">(</span><span class="token keyword">func</span><span class="token punctuation">(</span>c <span class="token operator">*</span>Car<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">		result<span class="token punctuation">[</span>ix<span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token function">f</span><span class="token punctuation">(</span>c<span class="token punctuation">)</span></span>
<span class="line">		ix<span class="token operator">++</span></span>
<span class="line">	<span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token keyword">return</span> result</span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">func</span> <span class="token function">MakeSortedAppender</span><span class="token punctuation">(</span>manufacturers <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token builtin">string</span><span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token keyword">func</span><span class="token punctuation">(</span>car <span class="token operator">*</span>Car<span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span>Cars<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">	<span class="token comment">// Prepare maps of sorted cars.</span></span>
<span class="line">	sortedCars <span class="token operator">:=</span> <span class="token function">make</span><span class="token punctuation">(</span><span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span>Cars<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">	<span class="token keyword">for</span> <span class="token boolean">_</span><span class="token punctuation">,</span> m <span class="token operator">:=</span> <span class="token keyword">range</span> manufacturers <span class="token punctuation">{</span></span>
<span class="line">		sortedCars<span class="token punctuation">[</span>m<span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token function">make</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token operator">*</span>Car<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line">	sortedCars<span class="token punctuation">[</span><span class="token string">"Default"</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token function">make</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token operator">*</span>Car<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">	<span class="token comment">// Prepare appender function:</span></span>
<span class="line">	appender <span class="token operator">:=</span> <span class="token keyword">func</span><span class="token punctuation">(</span>c <span class="token operator">*</span>Car<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">		<span class="token keyword">if</span> <span class="token boolean">_</span><span class="token punctuation">,</span> ok <span class="token operator">:=</span> sortedCars<span class="token punctuation">[</span>c<span class="token punctuation">.</span>Manufacturer<span class="token punctuation">]</span><span class="token punctuation">;</span> ok <span class="token punctuation">{</span></span>
<span class="line">			sortedCars<span class="token punctuation">[</span>c<span class="token punctuation">.</span>Manufacturer<span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token function">append</span><span class="token punctuation">(</span>sortedCars<span class="token punctuation">[</span>c<span class="token punctuation">.</span>Manufacturer<span class="token punctuation">]</span><span class="token punctuation">,</span> c<span class="token punctuation">)</span></span>
<span class="line">		<span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span></span>
<span class="line">			sortedCars<span class="token punctuation">[</span><span class="token string">"Default"</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token function">append</span><span class="token punctuation">(</span>sortedCars<span class="token punctuation">[</span><span class="token string">"Default"</span><span class="token punctuation">]</span><span class="token punctuation">,</span> c<span class="token punctuation">)</span></span>
<span class="line">		<span class="token punctuation">}</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line">	<span class="token keyword">return</span> appender<span class="token punctuation">,</span> sortedCars</span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>输出：</p>
<div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text" data-title="text"><pre v-pre><code><span class="line">AllCars:  [0xf8400038a0 0xf840003bd0 0xf840003ba0 0xf840003b70]</span>
<span class="line">New BMWs:  [0xf840003bd0]</span>
<span class="line">Map sortedCars:  map[Default:[0xf840003ba0] Jaguar:[] Land Rover:[] BMW:[0xf840003bd0 0xf840003b70] Aston Martin:[] Ford:[0xf8400038a0]]</span>
<span class="line">We have  2  BMWs</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


