<template><div><h1 id="_13-6-启动外部命令和程序" tabindex="-1"><a class="header-anchor" href="#_13-6-启动外部命令和程序"><span>13.6 启动外部命令和程序</span></a></h1>
<p><code v-pre>os</code> 包有一个 <code v-pre>StartProcess</code> 函数可以调用或启动外部系统命令和二进制可执行文件；它的第一个参数是要运行的进程，第二个参数用来传递选项或参数，第三个参数是含有系统环境基本信息的结构体。</p>
<p>这个函数返回被启动进程的 id (pid)，或者启动失败返回错误。</p>
<p><code v-pre>exec</code> 包中也有同样功能的更简单的结构体和函数；主要是 <code v-pre>exec.Command(name string, arg ...string)</code> 和 <code v-pre>Run()</code>。首先需要用系统命令或可执行文件的名字创建一个 <code v-pre>Command</code> 对象，然后用这个对象作为接收者调用 <code v-pre>Run()</code>。下面的程序（因为是执行 Linux 命令，只能在 Linux 下面运行）演示了它们的使用：</p>
<p>示例 13.6 <a href="examples/chapter_13/exec.go">exec.go</a>：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token comment">// exec.go</span></span>
<span class="line"><span class="token keyword">package</span> main</span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">(</span></span>
<span class="line">	<span class="token string">"fmt"</span></span>
<span class="line">    <span class="token string">"os/exec"</span></span>
<span class="line">	<span class="token string">"os"</span></span>
<span class="line"><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">func</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line"><span class="token comment">// 1) os.StartProcess //</span></span>
<span class="line"><span class="token comment">/*********************/</span></span>
<span class="line"><span class="token comment">/* Linux: */</span></span>
<span class="line">env <span class="token operator">:=</span> os<span class="token punctuation">.</span><span class="token function">Environ</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">procAttr <span class="token operator">:=</span> <span class="token operator">&amp;</span>os<span class="token punctuation">.</span>ProcAttr<span class="token punctuation">{</span></span>
<span class="line">			Env<span class="token punctuation">:</span> env<span class="token punctuation">,</span></span>
<span class="line">			Files<span class="token punctuation">:</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token operator">*</span>os<span class="token punctuation">.</span>File<span class="token punctuation">{</span></span>
<span class="line">				os<span class="token punctuation">.</span>Stdin<span class="token punctuation">,</span></span>
<span class="line">				os<span class="token punctuation">.</span>Stdout<span class="token punctuation">,</span></span>
<span class="line">				os<span class="token punctuation">.</span>Stderr<span class="token punctuation">,</span></span>
<span class="line">			<span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">		<span class="token punctuation">}</span></span>
<span class="line"><span class="token comment">// 1st example: list files</span></span>
<span class="line">pid<span class="token punctuation">,</span> err <span class="token operator">:=</span> os<span class="token punctuation">.</span><span class="token function">StartProcess</span><span class="token punctuation">(</span><span class="token string">"/bin/ls"</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token builtin">string</span><span class="token punctuation">{</span><span class="token string">"ls"</span><span class="token punctuation">,</span> <span class="token string">"-l"</span><span class="token punctuation">}</span><span class="token punctuation">,</span> procAttr<span class="token punctuation">)</span>  </span>
<span class="line"><span class="token keyword">if</span> err <span class="token operator">!=</span> <span class="token boolean">nil</span> <span class="token punctuation">{</span></span>
<span class="line">		fmt<span class="token punctuation">.</span><span class="token function">Printf</span><span class="token punctuation">(</span><span class="token string">"Error %v starting process!"</span><span class="token punctuation">,</span> err<span class="token punctuation">)</span>  <span class="token comment">//</span></span>
<span class="line">		os<span class="token punctuation">.</span><span class="token function">Exit</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line">fmt<span class="token punctuation">.</span><span class="token function">Printf</span><span class="token punctuation">(</span><span class="token string">"The process id is %v"</span><span class="token punctuation">,</span> pid<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>输出：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line">The process id is <span class="token operator">&amp;</span><span class="token punctuation">{</span><span class="token number">2054</span> <span class="token number">0</span><span class="token punctuation">}</span>total <span class="token number">2056</span></span>
<span class="line"><span class="token operator">-</span>rwxr<span class="token operator">-</span>xr<span class="token operator">-</span>x <span class="token number">1</span> ivo ivo <span class="token number">1157555</span> <span class="token number">2011</span><span class="token operator">-</span><span class="token number">07</span><span class="token operator">-</span><span class="token number">04</span> <span class="token number">16</span><span class="token punctuation">:</span><span class="token number">48</span> Mieken_exec</span>
<span class="line"><span class="token operator">-</span>rw<span class="token operator">-</span>r<span class="token operator">--</span>r<span class="token operator">--</span> <span class="token number">1</span> ivo ivo    <span class="token number">2124</span> <span class="token number">2011</span><span class="token operator">-</span><span class="token number">07</span><span class="token operator">-</span><span class="token number">04</span> <span class="token number">16</span><span class="token punctuation">:</span><span class="token number">48</span> Mieken_exec<span class="token punctuation">.</span><span class="token keyword">go</span></span>
<span class="line"><span class="token operator">-</span>rw<span class="token operator">-</span>r<span class="token operator">--</span>r<span class="token operator">--</span> <span class="token number">1</span> ivo ivo   <span class="token number">18528</span> <span class="token number">2011</span><span class="token operator">-</span><span class="token number">07</span><span class="token operator">-</span><span class="token number">04</span> <span class="token number">16</span><span class="token punctuation">:</span><span class="token number">48</span> Mieken_exec_go_<span class="token punctuation">.</span><span class="token number">6</span></span>
<span class="line"><span class="token operator">-</span>rwxr<span class="token operator">-</span>xr<span class="token operator">-</span>x <span class="token number">1</span> ivo ivo  <span class="token number">913920</span> <span class="token number">2011</span><span class="token operator">-</span><span class="token number">06</span><span class="token operator">-</span><span class="token number">03</span> <span class="token number">16</span><span class="token punctuation">:</span><span class="token number">13</span> <span class="token builtin">panic</span><span class="token punctuation">.</span>exe</span>
<span class="line"><span class="token operator">-</span>rw<span class="token operator">-</span>r<span class="token operator">--</span>r<span class="token operator">--</span> <span class="token number">1</span> ivo ivo     <span class="token number">180</span> <span class="token number">2011</span><span class="token operator">-</span><span class="token number">04</span><span class="token operator">-</span><span class="token number">11</span> <span class="token number">20</span><span class="token punctuation">:</span><span class="token number">39</span> <span class="token builtin">panic</span><span class="token punctuation">.</span><span class="token keyword">go</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token comment">// 2nd example: show all processes</span></span>
<span class="line">pid<span class="token punctuation">,</span> err <span class="token operator">=</span> os<span class="token punctuation">.</span><span class="token function">StartProcess</span><span class="token punctuation">(</span><span class="token string">"/bin/ps"</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token builtin">string</span><span class="token punctuation">{</span><span class="token string">"ps"</span><span class="token punctuation">,</span> <span class="token string">"-e"</span><span class="token punctuation">,</span> <span class="token string">"-opid,ppid,comm"</span><span class="token punctuation">}</span><span class="token punctuation">,</span> procAttr<span class="token punctuation">)</span>  </span>
<span class="line"></span>
<span class="line"><span class="token keyword">if</span> err <span class="token operator">!=</span> <span class="token boolean">nil</span> <span class="token punctuation">{</span></span>
<span class="line">		fmt<span class="token punctuation">.</span><span class="token function">Printf</span><span class="token punctuation">(</span><span class="token string">"Error %v starting process!"</span><span class="token punctuation">,</span> err<span class="token punctuation">)</span>  <span class="token comment">//</span></span>
<span class="line">		os<span class="token punctuation">.</span><span class="token function">Exit</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">fmt<span class="token punctuation">.</span><span class="token function">Printf</span><span class="token punctuation">(</span><span class="token string">"The process id is %v"</span><span class="token punctuation">,</span> pid<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go" data-title="go"><pre v-pre><code><span class="line"><span class="token comment">// 2) exec.Run //</span></span>
<span class="line"><span class="token comment">/***************/</span></span>
<span class="line"><span class="token comment">// Linux:  OK, but not for ls ?</span></span>
<span class="line"><span class="token comment">// cmd := exec.Command("ls", "-l")  // no error, but doesn't show anything ?</span></span>
<span class="line"><span class="token comment">// cmd := exec.Command("ls")  		// no error, but doesn't show anything ?</span></span>
<span class="line">	cmd <span class="token operator">:=</span> exec<span class="token punctuation">.</span><span class="token function">Command</span><span class="token punctuation">(</span><span class="token string">"gedit"</span><span class="token punctuation">)</span>  <span class="token comment">// this opens a gedit-window</span></span>
<span class="line">	err <span class="token operator">=</span> cmd<span class="token punctuation">.</span><span class="token function">Run</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token keyword">if</span> err <span class="token operator">!=</span> <span class="token boolean">nil</span> <span class="token punctuation">{</span></span>
<span class="line">		fmt<span class="token punctuation">.</span><span class="token function">Printf</span><span class="token punctuation">(</span><span class="token string">"Error %v executing command!"</span><span class="token punctuation">,</span> err<span class="token punctuation">)</span></span>
<span class="line">		os<span class="token punctuation">.</span><span class="token function">Exit</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line">	fmt<span class="token punctuation">.</span><span class="token function">Printf</span><span class="token punctuation">(</span><span class="token string">"The command is %v"</span><span class="token punctuation">,</span> cmd<span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">// The command is &amp;{/bin/ls [ls -l] []  &lt;nil> &lt;nil> &lt;nil> 0xf840000210 &lt;nil> true [0xf84000ea50 0xf84000e9f0 0xf84000e9c0] [0xf84000ea50 0xf84000e9f0 0xf84000e9c0] [] [] 0xf8400128c0}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"><span class="token comment">// in Windows: uitvoering: Error fork/exec /bin/ls: The system cannot find the path specified. starting process!</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="链接" tabindex="-1"><a class="header-anchor" href="#链接"><span>链接</span></a></h2>
<ul>
<li><RouteLink to="/chapter-3/directory.html">目录</RouteLink></li>
<li>上一节：<RouteLink to="/chapter-3/13.5.html">一种用闭包处理错误的模式</RouteLink></li>
<li>下一节：<RouteLink to="/chapter-3/13.7.html">Go 中的单元测试和基准测试</RouteLink></li>
</ul>
</div></template>


